export const FILTER_BAR = "FILTER_BAR";
// export const GET_USER_LOCATION = "GET_USER_LOCATION";
// export const GET_LOCATION_RESTAURANTS = "GET_LOCATION_RESTAURANTS";
// export const RESTAURANT_SEARCH = "RESTAURANT_SEARCH";
